### PR TITLE
remove gepetto-viewer-server, fix #74

### LINKED ISSUE #74: Remove gepetto-viewer-server
As the bug related to DAE should be fixed now, I propose to remove `gepetto-viewer-server`. It should simplify a few things in the code.

### PR DESCRIPTION
**Pull request by nim65s**

### CODE REVIEW

**Comment by jcarpent** [comment]
If you remove it, remove it deeply. Which means the cpp files that we do want to support anymore.

**Comment by jcarpent** [comment]
fix both #74 and #83

**Comment by jmirabel** [comment]
The changes are not as simple as removing a cpp file.

The most interesting is that `gepetto::gui::WindowsManager` and `graphics::WindowsManager` can be merged. But this can be kept as such for now.

**Comment by nim65s** [comment]
I'll merge this one, make a release (as @jmirabel requested it), and open a new issue about merging the classes

**Pull request merged**
